sudo: required

services:
  - docker

docker run -it -p 5011:80 --name web.a ykandrirody/docker-netmvc-a

script:
  # Build image
  - docker build -t ykandrirody/docker-netmvc-a .
  # Test for single database
  - docker run --name testwebserver -d -p 9090:80 ykandrirody/docker-netmvc-a
  - docker ps -a
  - curl http://127.0.0.1:9090/ | grep -q 'Web Server A'
